export const SET_OPEN_ID = 'SET_OPEN_ID'

export const SET_THEME = 'SET_THEME'

export const FOLLOW_NOVEL = 'FOLLOW_NOVEL'

export const CHANGE_SOURCE = 'CHANGE_SOURCE'

export const CHANGE_READ_CHAPTER = 'CHANGE_READ_CHAPTER'
